### ISSUE TITLE
[question] Storing producer and consumer as struct's fields

### ISSUE THREAD

**Issue by Antiarchitect** [agerasev/async-ringbuf#1]
Hi @agerasev!
Assume I want to store AsyncProducer and AsyncConsumer as struct fields. Is there any way to describe the types before I create AsyncHeapRb? AsyncProducer and AsyncConsumer require RbRef as generic argument.

**Comment by agerasev** [comment]
Hi!
Producer and consumer returned by `AsyncHeapRb<T>::split()` can be written as `AsyncProducer<T, Arc<AsyncHeapRb<T>>>` and `AsyncConsumer<T, Arc<AsyncHeapRb<T>>>`.
Yeah, it's pretty ugly. It might be worth adding aliases 🤔

**Comment by Antiarchitect** [comment]
Thank you for clarification @agerasev!
I think async-ringbuf is not exactly that I'm looking for :) My goal was to find async circular queue with fixed capacity rewriting old entries on overflow. I need this in order to protect my server against slow clients consuming telemetry not fast enough. The goal is to make telemetry lag fixed in size and short. Seems your ringbuf's producer will wait asynchronously if the buffer is full which doesn't fits my needs. Hope I can write async circular queue by myself based on https://crates.io/crates/circular-queue Anyway thank you so much for your project :)
